// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8WDgDYsYpex5xQ5Jyh9VD9HmfmIFLmhk',
    appId: '1:3959678082:web:f3d2e6781fc2b558d5409b',
    messagingSenderId: '3959678082',
    projectId: 'smart-swine',
    authDomain: 'smart-swine.firebaseapp.com',
    storageBucket: 'smart-swine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9Cu0cLe2pVe9dqhkg-O1DUsUgTyVTgo',
    appId: '1:3959678082:android:e7118aa9086919fad5409b',
    messagingSenderId: '3959678082',
    projectId: 'smart-swine',
    storageBucket: 'smart-swine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8okxiQyPPAnkLOf297gjbLuoBnLdIFFc',
    appId: '1:3959678082:ios:883ef8157e983464d5409b',
    messagingSenderId: '3959678082',
    projectId: 'smart-swine',
    storageBucket: 'smart-swine.firebasestorage.app',
    iosBundleId: 'com.smartswinepoke.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8okxiQyPPAnkLOf297gjbLuoBnLdIFFc',
    appId: '1:3959678082:ios:50d8ca4c43c30163d5409b',
    messagingSenderId: '3959678082',
    projectId: 'smart-swine',
    storageBucket: 'smart-swine.firebasestorage.app',
    iosBundleId: 'com.example.smartSwine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8WDgDYsYpex5xQ5Jyh9VD9HmfmIFLmhk',
    appId: '1:3959678082:web:7e859eb1c7c6f01ad5409b',
    messagingSenderId: '3959678082',
    projectId: 'smart-swine',
    authDomain: 'smart-swine.firebaseapp.com',
    storageBucket: 'smart-swine.firebasestorage.app',
  );
}
